export enum NotificationType {
    // General
    INFO = 'INFO',
    SUCCESS = 'SUCCESS',
    WARNING = 'WARNING',
    ERROR = 'ERROR',
    
    // Tasks
    TASK_ASSIGNED = 'TASK_ASSIGNED',
    TASK_UPDATED = 'TASK_UPDATED',
    TASK_COMPLETED = 'TASK_COMPLETED',
    
    // Projects
    PROJECT_CREATED = 'PROJECT_CREATED',
    PROJECT_UPDATED = 'PROJECT_UPDATED',
    PROJECT_COMPLETED = 'PROJECT_COMPLETED',
    
    // Dispatches (Command Center)
    DISPATCH_RECEIVED = 'DISPATCH_RECEIVED',
    DISPATCH_RESOLVED = 'DISPATCH_RESOLVED',
    DISPATCH_CONVERTED_TO_TASK = 'DISPATCH_CONVERTED_TO_TASK',
    
    // Expenses
    EXPENSE_SUBMITTED = 'EXPENSE_SUBMITTED',
    EXPENSE_APPROVED = 'EXPENSE_APPROVED',
    EXPENSE_REJECTED = 'EXPENSE_REJECTED',
    
    // Time Entries
    TIME_ENTRY_SUBMITTED = 'TIME_ENTRY_SUBMITTED',
    TIME_ENTRY_APPROVED = 'TIME_ENTRY_APPROVED',
    TIME_ENTRY_REJECTED = 'TIME_ENTRY_REJECTED',
    
    // Invoices
    INVOICE_CREATED = 'INVOICE_CREATED',
    INVOICE_PAID = 'INVOICE_PAID',
    
    // Payments
    PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
    
    // Accounts Payable (Cuentas por Pagar)
    ACCOUNT_PAYABLE_DUE = 'ACCOUNT_PAYABLE_DUE',
    ACCOUNT_PAYABLE_PAID = 'ACCOUNT_PAYABLE_PAID',
    ACCOUNT_PAYABLE_OVERDUE = 'ACCOUNT_PAYABLE_OVERDUE',
    
    // Accounts Receivable (Cuentas por Cobrar)
    ACCOUNT_RECEIVABLE_DUE = 'ACCOUNT_RECEIVABLE_DUE',
    ACCOUNT_RECEIVABLE_PAID = 'ACCOUNT_RECEIVABLE_PAID',
    ACCOUNT_RECEIVABLE_OVERDUE = 'ACCOUNT_RECEIVABLE_OVERDUE',
    
    // Purchase Orders (Órdenes de Compra)
    PURCHASE_ORDER_CREATED = 'PURCHASE_ORDER_CREATED',
    PURCHASE_ORDER_APPROVED = 'PURCHASE_ORDER_APPROVED',
    PURCHASE_ORDER_REJECTED = 'PURCHASE_ORDER_REJECTED',
    PURCHASE_ORDER_PAID = 'PURCHASE_ORDER_PAID',
    
    // Requisitions (Requisiciones)
    REQUISITION_CREATED = 'REQUISITION_CREATED',
    REQUISITION_APPROVED = 'REQUISITION_APPROVED',
    REQUISITION_REJECTED = 'REQUISITION_REJECTED',
    
    // Quotes (Cotizaciones)
    QUOTE_CREATED = 'QUOTE_CREATED',
    QUOTE_ACCEPTED = 'QUOTE_ACCEPTED',
    QUOTE_REJECTED = 'QUOTE_REJECTED',
    QUOTE_EXPIRED = 'QUOTE_EXPIRED',
    
    // Recoveries (Recuperaciones)
    RECOVERY_CREATED = 'RECOVERY_CREATED',
    RECOVERY_COMPLETED = 'RECOVERY_COMPLETED',
    
    // Fixed Costs (Costos Fijos)
    FIXED_COST_DUE = 'FIXED_COST_DUE',
    
    // Prospects
    PROSPECT_CREATED = 'PROSPECT_CREATED',
    PROSPECT_STATUS_CHANGED = 'PROSPECT_STATUS_CHANGED',
    PROSPECT_ASSIGNED = 'PROSPECT_ASSIGNED',
    PROSPECT_CONVERTED_TO_CLIENT = 'PROSPECT_CONVERTED_TO_CLIENT',
    PROSPECT_NEEDS_ATTENTION = 'PROSPECT_NEEDS_ATTENTION',
}

